apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-app
spec:
  containers:
  - name: redis-container
    image: redis
    volumeMounts:
    - mountPath: "/my-data"
      name: "my-hostpath-vol"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: "my-hostpath-vol"
    hostPath:
      path: "/var/lib/2-persist"