apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      name: job-pod
    spec:
      containers:
      - name: busybox-container
        image: busybox
        command: ["bin/sh",  "-c", "for i in 1 2; do echo Lucky number $i = $((1 + RANDOM % 70)); done"]
      restartPolicy: Never
