apiVersion: v1
kind: Pod
metadata :
  name: redis-pod
  labels:
    apps: backend
spec:
  containers:
    - name: container-redis
      image: redis
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
