apiVersion: v1
kind: Pod
metadata :
  name: tomcat-pod
  namespace: backend
  labels:
    apps: app-java
spec:
  containers:
    - name: container-tomcat
      image: tomcat
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"